const products = [
    {
        id: 'm1',
        name: 'Spider-Man Venom T-Shirt',
        category: 'T-Shirts',
        hero: 'spiderman',
        price: 400,
        universe: 'marvel',
        img1: 'tsvenom1.jpg',
        img2: 'tsvenom2.jpg',
        img3: 'tsvenom3.jpg',
        img4: 'tshirtsize.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'm2',
        name: `Iron Man Suit-Up Men's Costume T-Shirt`,
        hero: 'ironman',
        category: 'T-Shirts',
        price: 450,
        universe: 'marvel',
        img1: 'tsironman1.jpg',
        img2: 'tsironman2.jpg',
        img3: 'tsironman3.jpg',
        img4: 'tshirtsize.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'm3',
        name: 'X-Men Distressed Symbol Grey T-Shirt',
        category: 'T-Shirts',
        hero: 'xmen',
        price: 350,
        universe: 'marvel',
        img1: 'tsxmensymbol1.jpg',
        img2: 'tsxmensymbol2.jpg',
        img3: 'tsxmensymbol3.jpg',
        img4: 'tshirtsize.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'm4',
        name: 'Captain America Distressed Shield Navy T-Shirt',
        category: 'T-Shirts',
        hero: 'captain america',
        price: 400,
        universe: 'marvel',
        img1: 'tscaptain1.jpg',
        img2: 'tscaptain2.jpg',
        img3: 'tscaptain3.jpg',
        img4: 'tshirtsize.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'm5',
        name: 'Miles Morales Spider-Man Hat',
        category: 'Hats',
        hero: 'spiderman',
        price: 200,
        universe: 'marvel',
        img1: 'cspiderman1.jpg',
        img2: 'cspiderman2.jpg',
        img3: 'cspiderman3.jpg',
        img4: 'cspiderman4.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'm6',
        name: 'Black Panther Fitted Mesh Back Hat',
        category: 'Hats',
        hero: 'black panther',
        price: 200,
        universe: 'marvel',
        img1: 'cblackpanther1.jpg',
        img2: 'cblackpanther2.jpg',
        img3: 'cblackpanther3.jpg',
        img4: 'cblackpanther4.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'm7',
        name: 'Punisher Woodland Camo Adjustable Hat',
        category: 'Hats',
        hero: 'punisher',
        price: 200,
        universe: 'marvel',
        img1: 'cpunisher1.jpg',
        img2: 'cpunisher2.jpg',
        img3: 'cpunisher3.jpg',
        img4: 'cpunisher4.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'm8',
        name: 'Marvel Sandal Slides',
        category: 'Footwear',
        hero: 'marvel',
        price: 150,
        universe: 'marvel',
        img1: 'fmarvel1.jpg',
        img2: 'fmarvel2.jpg',
        img3: 'fmarvel3.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['6', '7', '8']
    },
    {
        id: 'm9',
        name: 'Avengers Assemble Kids Lighted Canvas Shoes',
        category: 'Footwear',
        hero: 'marvel',
        price: 600,
        universe: 'marvel',
        img1: 'favengers1.jpg',
        img2: 'favengers2.jpg',
        img3: 'favengers3.jpg',
        img4: 'favengers4.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['4', '5', '6']
    },
    {
        id: 'm10',
        name: 'Doctor Strange Vinyl Figure',
        category: 'Figures',
        hero: 'doctorstrange',
        price: 150,
        universe: 'marvel',
        img1: 'fidoctor1.jpg',
        img2: 'fidoctor2.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Small', 'Large']
    },
    {
        id: 'm11',
        name: 'Marvel Comics The Wolverine Vinyl Figure',
        category: 'Figures',
        hero: 'wolverine',
        price: 150,
        universe: 'marvel',
        img1: 'fiwolverine1.jpg',
        img2: 'fiwolverine2.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Small', 'Large']
    },
    {
        id: 'm12',
        name: `Iron Man T-Shirt`,
        hero: 'ironman',
        category: 'T-Shirts',
        price: 350,
        universe: 'marvel',
        img1: 'ts2ironman1.jpg',
        img2: 'ts2ironman2.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'm13',
        name: 'Punisher T-Shirt',
        category: 'T-Shirts',
        hero: 'punisher',
        price: 350,
        universe: 'marvel',
        img1: 'tspunisher1.jpg',
        img2: 'tspunisher2.jpg',
        img3: 'tspunisher3.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'd1',
        name: 'Batman T-Shirt',
        category: 'T-Shirts',
        hero: 'batman',
        price: 350,
        universe: 'dc',
        img1: 'tsbatman1.jpg',
        img2: 'tsbatman2.jpg',
        img3: 'tsbatman3.jpg',
        img4: 'tshirtsize.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'd11',
        name: 'Flash T-Shirt',
        category: 'T-Shirts',
        hero: 'flash',
        price: 350,
        universe: 'dc',
        img1: 'tsflash1.jpg',
        img2: 'tsflash2.jpg',
        img3: 'tsflash3.jpg',
        img4: 'tshirtsize.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'd12',
        name: 'Wonder Woman Costume T-Shirt',
        category: 'T-Shirts',
        hero: 'wonder woman',
        price: 450,
        universe: 'dc',
        img1: 'tsww1.jpg',
        img2: 'tsww2.jpg',
        img3: 'tsww3.jpg',
        img4: 'tsww4.jpg',
        gender: 'women',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'd2',
        name: 'Batman Cap',
        category: 'Hats',
        hero: 'batman',
        price: 200,
        universe: 'dc',
        img1: 'hbatman1.jpg',
        img2: 'hbatman2.jpg',
        img3: 'hbatman3.jpg',
        img4: 'hbatman4.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'd3',
        name: 'Batman Cap',
        category: 'Hats',
        hero: 'batman',
        price: 200,
        universe: 'dc',
        img1: 'h2batman1.jpg',
        img2: 'h2batman2.jpg',
        img3: 'h2batman3.jpg',
        img4: 'h2batman4.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'd4',
        name: 'Superman Hoodie',
        category: 'Hoodies',
        hero: 'superman',
        price: 650,
        universe: 'dc',
        img1: 'hosuperman1.jpg',
        img2: 'hosuperman2.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL']
    },
    {
        id: 'd5',
        name: 'Flash Cap',
        category: 'Hats',
        hero: 'flash',
        price: 200,
        universe: 'dc',
        img1: 'hflash1.jpg',
        img2: 'hflash2.jpg',
        img3: 'hflash3.jpg',
        img4: 'hflash4.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'd6',
        name: 'Superman socks',
        category: 'Socks',
        hero: 'superman',
        price: 100,
        universe: 'dc',
        img1: 'ssuperman1.jpg',
        img2: 'ssuperman2.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'd7',
        name: 'Superman socks',
        category: 'Socks',
        hero: 'superman',
        price: 100,
        universe: 'dc',
        img1: 's2superman1.jpg',
        img2: 's2superman2.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'd8',
        name: 'Flash socks',
        category: 'Socks',
        hero: 'flash',
        price: 100,
        universe: 'dc',
        img1: 'sflash1.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'd9',
        name: 'Batman socks',
        category: 'Socks',
        hero: 'batman',
        price: 100,
        universe: 'dc',
        img1: 'sbatman1.jpg',
        img2: 'sbatman2.jpg',
        gender: 'men',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },
    {
        id: 'd10',
        name: 'Wonder Woman socks',
        category: 'Socks',
        hero: 'wonder woman',
        price: 100,
        universe: 'dc',
        img1: 'sww1.jpg',
        img2: 'sww2.jpg',
        gender: 'women',
        stock: 50,
        sizes: ['Kids', 'Adult']
    },

]

module.exports = {products}